kind: PersistentVolume
apiVersion: v1
metadata:
  name: consul-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: master
    path: /mnt/voranfs/datahub
  persistentVolumeReclaimPolicy: Retain
