kind: PersistentVolume
apiVersion: v1
metadata:
  name: d3 
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: master
    path: /mnt/voranfs/datahub/d3
  persistentVolumeReclaimPolicy: Retain
